### ISSUE TITLE
Propiedades pendientes

### ISSUE THREAD

**Issue by thessaly** [cientopolis/appropedia-surgery#1]
Skill
- [x] *requiredHours* (float)

Medical skill
- [x] *isFirstAid* (boolean)
- [x] *bodyPart* (literal)
- [x] *pathology* (literal)
- [x] *interventionType* (literal)
- [x] *specialty* (literal)

Course
- [x] course has *learning object* (skill)

Media
- [x] *duration* (float)

**Comment by magictowers** [comment]
Done
